<!DOCTYPE html>
<html>
    <body>
        <div id="root"></div>      

        <!-- React CDN import -->
        <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>

        <!-- Babel CDN import -->
        <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>


        <script type="text/babel">
            const rootElement = document.getElementById("root");

            // Error Boundary 컴포넌트 : Catch Error 해서 보여주기
            // fallback이란? : 에러가 났을 때 보여줄 컴포넌트
            class ErrorBoundary extends React.Component {
                state = { error : null};
                static getDerivedStateFromError(error) {
                    return { error };
                };

                render() {
                    const {error} = this.state;
                    if(error) {
                        // return this.props.fallback;
                        return <this.props.fallback error={error} />;
                    }
                    return this.props.children;
                };
            };

            const Child = () => {
                throw new Error('Something wrong...');
                return <p>Child!!!</p>
            }

            const Fallback = ({error}) => {
                return <p>{error.message}</p>;
            }

            const App = () => {
                return (
                    <>
                        <p>App</p>
                        <br/>
                        {/*<ErrorBoundary fallback ={<p>There is some error...</p>}>*/}
                        <ErrorBoundary fallback ={Fallback}>
                            <Child/>
                        </ErrorBoundary>
                    </>
                );
            };

            ReactDOM.render(<App />, document.getElementById("root"));
        </script>


    </body>
</html>


